name: Python CI

on:
  push:
    # branches: 後面要加一個空格，不然會報錯
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        # python-version: [3.8, 3.9, 3.10, 3.11]
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
          # if [ -f requirements.txt ]; then pip install -r requirements.txt;fi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
          # if [ -f pytest.ini ]; then pytest; fi
        run: |
          pytest
    
